
const AUTH0 = {
    // Generated by Vladimir's developer account in auth0.com, now.
    CLIENT_ID: 'WP1TVYwlG3Z1kT3J6U7vOVB3a3vmBAu2', // Change it to your app client id
    DOMAIN:'iotify.us.auth0.com', // Change it to your auth0 domain
    CALLBACK:'http://localhost:3000' // Change it to your production url
};

export { AUTH0 };
