
import { Meteor } from 'meteor/meteor'

const AUTH0 = {
    // Generated by Vladimir's developer account in auth0.com, now.
    CLIENT_ID: Meteor.settings.public.AUTH0.CLIENT_ID, // Change it to your app client id
    DOMAIN: Meteor.settings.public.AUTH0.DOMAIN, // Change it to your auth0 domain
    CALLBACK: Meteor.settings.public.AUTH0.CALLBACK // Change it to your production url
};

export { AUTH0 };
